version: "3.7"

services:
  mautrix-telegram:
    container_name: mautrix-telegram
    image: mautrix-telegram-custom
    restart: unless-stopped
    volumes:
    - $PWD/data:/data
    networks:
    - traefik_proxy

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
